//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ConditionalTokenVault
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const conditionalTokenVaultAbi = [
  {
    type: "constructor",
    inputs: [{ name: "_usdc", internalType: "address", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "USDC",
    outputs: [{ name: "", internalType: "contract IERC20", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "admin",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "account", internalType: "address", type: "address" },
      { name: "id", internalType: "uint256", type: "uint256" },
    ],
    name: "balanceOf",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "accounts", internalType: "address[]", type: "address[]" },
      { name: "ids", internalType: "uint256[]", type: "uint256[]" },
    ],
    name: "balanceOfBatch",
    outputs: [{ name: "", internalType: "uint256[]", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "from", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "outcomeCount", internalType: "uint256", type: "uint256" },
    ],
    name: "burnOutcomeTokens",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "from", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "burnPair",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "factory",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fpmm",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "getCollateral",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "account", internalType: "address", type: "address" },
      { name: "operator", internalType: "address", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "isResolved",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    name: "markets",
    outputs: [
      { name: "resolved", internalType: "bool", type: "bool" },
      { name: "winningOutcomeIndex", internalType: "uint256", type: "uint256" },
      { name: "totalCollateral", internalType: "uint256", type: "uint256" },
      { name: "outcomeCount", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "outcomeCount", internalType: "uint256", type: "uint256" },
    ],
    name: "mintOutcomeTokens",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "mintPair",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "noTokenId",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "outcomeIndex", internalType: "uint256", type: "uint256" },
    ],
    name: "outcomeTokenId",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "winningIsYes", internalType: "bool", type: "bool" },
    ],
    name: "resolve",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "winningOutcomeIndex", internalType: "uint256", type: "uint256" },
    ],
    name: "resolveOutcome",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "ids", internalType: "uint256[]", type: "uint256[]" },
      { name: "values", internalType: "uint256[]", type: "uint256[]" },
      { name: "data", internalType: "bytes", type: "bytes" },
    ],
    name: "safeBatchTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "id", internalType: "uint256", type: "uint256" },
      { name: "value", internalType: "uint256", type: "uint256" },
      { name: "data", internalType: "bytes", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "operator", internalType: "address", type: "address" },
      { name: "approved", internalType: "bool", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_factory", internalType: "address", type: "address" }],
    name: "setFactory",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_fpmm", internalType: "address", type: "address" }],
    name: "setFpmm",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "interfaceId", internalType: "bytes4", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "totalSupply",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_newAdmin", internalType: "address", type: "address" }],
    name: "transferAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "uri",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "yesTokenId",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "operator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "approved", internalType: "bool", type: "bool", indexed: false },
    ],
    name: "ApprovalForAll",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "winningIsYes",
        internalType: "bool",
        type: "bool",
        indexed: false,
      },
    ],
    name: "MarketResolved",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      { name: "from", internalType: "address", type: "address", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PairBurned",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      { name: "to", internalType: "address", type: "address", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PairMinted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "operator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "from", internalType: "address", type: "address", indexed: true },
      { name: "to", internalType: "address", type: "address", indexed: true },
      {
        name: "ids",
        internalType: "uint256[]",
        type: "uint256[]",
        indexed: false,
      },
      {
        name: "values",
        internalType: "uint256[]",
        type: "uint256[]",
        indexed: false,
      },
    ],
    name: "TransferBatch",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "operator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "from", internalType: "address", type: "address", indexed: true },
      { name: "to", internalType: "address", type: "address", indexed: true },
      { name: "id", internalType: "uint256", type: "uint256", indexed: false },
      {
        name: "value",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "TransferSingle",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "value", internalType: "string", type: "string", indexed: false },
      { name: "id", internalType: "uint256", type: "uint256", indexed: true },
    ],
    name: "URI",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      { name: "user", internalType: "address", type: "address", indexed: true },
      {
        name: "tokens",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "usdcPayout",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "WinningsRedeemed",
  },
  {
    type: "error",
    inputs: [
      { name: "sender", internalType: "address", type: "address" },
      { name: "balance", internalType: "uint256", type: "uint256" },
      { name: "needed", internalType: "uint256", type: "uint256" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "ERC1155InsufficientBalance",
  },
  {
    type: "error",
    inputs: [{ name: "approver", internalType: "address", type: "address" }],
    name: "ERC1155InvalidApprover",
  },
  {
    type: "error",
    inputs: [
      { name: "idsLength", internalType: "uint256", type: "uint256" },
      { name: "valuesLength", internalType: "uint256", type: "uint256" },
    ],
    name: "ERC1155InvalidArrayLength",
  },
  {
    type: "error",
    inputs: [{ name: "operator", internalType: "address", type: "address" }],
    name: "ERC1155InvalidOperator",
  },
  {
    type: "error",
    inputs: [{ name: "receiver", internalType: "address", type: "address" }],
    name: "ERC1155InvalidReceiver",
  },
  {
    type: "error",
    inputs: [{ name: "sender", internalType: "address", type: "address" }],
    name: "ERC1155InvalidSender",
  },
  {
    type: "error",
    inputs: [
      { name: "operator", internalType: "address", type: "address" },
      { name: "owner", internalType: "address", type: "address" },
    ],
    name: "ERC1155MissingApprovalForAll",
  },
  { type: "error", inputs: [], name: "InsufficientBalance" },
  { type: "error", inputs: [], name: "MarketAlreadyResolved" },
  { type: "error", inputs: [], name: "MarketNotResolved" },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
  { type: "error", inputs: [], name: "Unauthorized" },
  { type: "error", inputs: [], name: "ZeroAmount" },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// VerityFPMM
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const verityFpmmAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_vault", internalType: "address", type: "address" },
      { name: "_usdc", internalType: "address", type: "address" },
      { name: "_treasury", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "BPS_DENOMINATOR",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "PRECISION",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "USDC",
    outputs: [{ name: "", internalType: "contract IERC20", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "VAULT",
    outputs: [
      {
        name: "",
        internalType: "contract ConditionalTokenVault",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "usdcAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "addLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "beneficiary", internalType: "address", type: "address" },
      { name: "usdcAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "addLiquidityFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "admin",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "isYes", internalType: "bool", type: "bool" },
      { name: "usdcAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "buy",
    outputs: [{ name: "tokensOut", internalType: "uint256", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "outcomeIndex", internalType: "uint256", type: "uint256" },
      { name: "usdcAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "buyOutcome",
    outputs: [{ name: "tokensOut", internalType: "uint256", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "user", internalType: "address", type: "address" },
    ],
    name: "canRemoveLiquidity",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "claimCreatorLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "claimPreMarketLpShares",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "outcomeCount", internalType: "uint256", type: "uint256" },
    ],
    name: "createPool",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "createPool",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "creatorMinLock",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "factory",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feeBps",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "getNoPrice",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "getOutcomeBalances",
    outputs: [{ name: "", internalType: "uint256[]", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "getPoolBalances",
    outputs: [
      { name: "yesBalance", internalType: "uint256", type: "uint256" },
      { name: "noBalance", internalType: "uint256", type: "uint256" },
      { name: "totalLpShares", internalType: "uint256", type: "uint256" },
      { name: "totalDeposited", internalType: "uint256", type: "uint256" },
      { name: "active", internalType: "bool", type: "bool" },
      { name: "resolved", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "getYesPrice",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "bytes32", type: "bytes32" },
      { name: "", internalType: "address", type: "address" },
    ],
    name: "lpDepositTime",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "lpFeeShare",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "lpLockDuration",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "bytes32", type: "bytes32" },
      { name: "", internalType: "address", type: "address" },
    ],
    name: "lpShares",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "markResolved",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "minPoolBalance",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "x", internalType: "uint256", type: "uint256" },
      { name: "n", internalType: "uint256", type: "uint256" },
    ],
    name: "nthRoot",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155BatchReceived",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155Received",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    name: "pools",
    outputs: [
      { name: "yesBalance", internalType: "uint256", type: "uint256" },
      { name: "noBalance", internalType: "uint256", type: "uint256" },
      { name: "totalLpShares", internalType: "uint256", type: "uint256" },
      { name: "creatorShares", internalType: "uint256", type: "uint256" },
      { name: "creator", internalType: "address", type: "address" },
      { name: "collectedFeesLp", internalType: "uint256", type: "uint256" },
      {
        name: "collectedFeesTreasury",
        internalType: "uint256",
        type: "uint256",
      },
      { name: "totalDeposited", internalType: "uint256", type: "uint256" },
      { name: "active", internalType: "bool", type: "bool" },
      { name: "resolved", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "shareAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "removeLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "isYes", internalType: "bool", type: "bool" },
      { name: "tokenAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "sell",
    outputs: [{ name: "usdcOut", internalType: "uint256", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "outcomeIndex", internalType: "uint256", type: "uint256" },
      { name: "tokenAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "sellOutcome",
    outputs: [{ name: "usdcOut", internalType: "uint256", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_factory", internalType: "address", type: "address" }],
    name: "setFactory",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_feeBps", internalType: "uint256", type: "uint256" }],
    name: "setFeeBps",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_lpFeeShare", internalType: "uint256", type: "uint256" },
      { name: "_treasuryFeeShare", internalType: "uint256", type: "uint256" },
    ],
    name: "setFeeShares",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_duration", internalType: "uint256", type: "uint256" }],
    name: "setLpLockDuration",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_minPoolBalance", internalType: "uint256", type: "uint256" },
      { name: "_creatorMinLock", internalType: "uint256", type: "uint256" },
    ],
    name: "setPoolLimits",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_treasury", internalType: "address", type: "address" }],
    name: "setTreasury",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "balances", internalType: "uint256[]", type: "uint256[]" },
      { name: "outcomeIndex", internalType: "uint256", type: "uint256" },
      { name: "tokenAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "solveSellGrossUsdc",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [{ name: "interfaceId", internalType: "bytes4", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_newAdmin", internalType: "address", type: "address" }],
    name: "transferAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "treasury",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "treasuryFeeShare",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "creator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "yesOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "noOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "CreatorLiquidityClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newFeeBps",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeeBpsUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newLpShare",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newTreasuryShare",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeeSharesUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "treasuryAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeesWithdrawn",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "provider",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "usdcAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "sharesMinted",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "LiquidityAdded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "provider",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sharesBurned",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "yesOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "noOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "LiquidityRemoved",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newDuration",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "LpLockDurationUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "totalDeposited",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PoolActivated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "creator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "initialUsdc",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PoolCreated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newMinPoolBalance",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newCreatorMinLock",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PoolLimitsUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      { name: "lp", internalType: "address", type: "address", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PreMarketLPSharesClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "buyer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "isYes", internalType: "bool", type: "bool", indexed: false },
      {
        name: "usdcIn",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "tokensOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      { name: "fee", internalType: "uint256", type: "uint256", indexed: false },
    ],
    name: "TokensBought",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "seller",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "isYes", internalType: "bool", type: "bool", indexed: false },
      {
        name: "tokensIn",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "usdcOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      { name: "fee", internalType: "uint256", type: "uint256", indexed: false },
    ],
    name: "TokensSold",
  },
  { type: "error", inputs: [], name: "CreatorCannotWithdraw" },
  { type: "error", inputs: [], name: "InsufficientBalance" },
  { type: "error", inputs: [], name: "InsufficientDeposit" },
  { type: "error", inputs: [], name: "InsufficientShares" },
  { type: "error", inputs: [], name: "InvalidPool" },
  { type: "error", inputs: [], name: "InvalidValue" },
  { type: "error", inputs: [], name: "LPLockActive" },
  { type: "error", inputs: [], name: "NotCreator" },
  { type: "error", inputs: [], name: "PoolAlreadyExists" },
  { type: "error", inputs: [], name: "PoolNotActive" },
  { type: "error", inputs: [], name: "PoolNotResolved" },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
  { type: "error", inputs: [], name: "Unauthorized" },
  { type: "error", inputs: [], name: "ZeroAmount" },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// VerityMarketFactory
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const verityMarketFactoryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_fpmm", internalType: "address", type: "address" },
      { name: "_vault", internalType: "address", type: "address" },
      { name: "_usdc", internalType: "address", type: "address" },
      { name: "_pyth", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "FPMM",
    outputs: [
      { name: "", internalType: "contract VerityFPMM", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "PYTH",
    outputs: [{ name: "", internalType: "contract IPyth", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "USDC",
    outputs: [{ name: "", internalType: "contract IERC20", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "VAULT",
    outputs: [
      {
        name: "",
        internalType: "contract ConditionalTokenVault",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "admin",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "allMarketIds",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "user", internalType: "address", type: "address" },
    ],
    name: "claimPreMarketDeposit",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "claimRefund",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "creatorLpAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "createMarketPreDeposit",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "beneficiary", internalType: "address", type: "address" },
      { name: "creatorLpAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "createMarketPreDepositFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "depositPreMarketLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "beneficiary", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "depositPreMarketLiquidityFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    name: "escrowBalances",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getMarketCount",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "isFundingExpired",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "isMarketActive",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "marketCreationFee",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    name: "marketRegistry",
    outputs: [
      { name: "creator", internalType: "address", type: "address" },
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "fundingDeadline", internalType: "uint256", type: "uint256" },
      { name: "registered", internalType: "bool", type: "bool" },
      { name: "funded", internalType: "bool", type: "bool" },
      { name: "resolved", internalType: "bool", type: "bool" },
      { name: "voided", internalType: "bool", type: "bool" },
      { name: "outcomeCount", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "optimisticResolver",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "bytes32", type: "bytes32" },
      { name: "", internalType: "address", type: "address" },
    ],
    name: "preMarketDeposits",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    name: "pythMarkets",
    outputs: [
      { name: "priceFeedId", internalType: "bytes32", type: "bytes32" },
      { name: "targetPrice", internalType: "int64", type: "int64" },
      { name: "resolveAbove", internalType: "bool", type: "bool" },
      { name: "isPythMarket", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "creator", internalType: "address", type: "address" },
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "fundingDeadline", internalType: "uint256", type: "uint256" },
    ],
    name: "registerMarket",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "creator", internalType: "address", type: "address" },
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "fundingDeadline", internalType: "uint256", type: "uint256" },
      { name: "outcomeCount", internalType: "uint256", type: "uint256" },
    ],
    name: "registerMarket",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "creator", internalType: "address", type: "address" },
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "fundingDeadline", internalType: "uint256", type: "uint256" },
      { name: "priceFeedId", internalType: "bytes32", type: "bytes32" },
      { name: "targetPrice", internalType: "int64", type: "int64" },
      { name: "resolveAbove", internalType: "bool", type: "bool" },
    ],
    name: "registerPythMarket",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "winningIsYes", internalType: "bool", type: "bool" },
    ],
    name: "resolveMarket",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "winningOutcomeIndex", internalType: "uint256", type: "uint256" },
    ],
    name: "resolveMarketFromResolver",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "winningOutcomeIndex", internalType: "uint256", type: "uint256" },
    ],
    name: "resolveMarketOutcome",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "priceUpdate", internalType: "bytes[]", type: "bytes[]" },
    ],
    name: "resolveMarketWithPyth",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [{ name: "_fee", internalType: "uint256", type: "uint256" }],
    name: "setMarketCreationFee",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_resolver", internalType: "address", type: "address" }],
    name: "setOptimisticResolver",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newAdmin", internalType: "address", type: "address" }],
    name: "transferAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "voidMarket",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newFee",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MarketCreationFeeUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "creator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MarketFunded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "creator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MarketPreDepositCreated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "creator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "deadline",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fundingDeadline",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MarketRegistered",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "winningIsYes",
        internalType: "bool",
        type: "bool",
        indexed: false,
      },
    ],
    name: "MarketResolved",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
    ],
    name: "MarketVoided",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "resolver",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "OptimisticResolverUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "priceFeedId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
      {
        name: "targetPrice",
        internalType: "int64",
        type: "int64",
        indexed: false,
      },
      {
        name: "resolveAbove",
        internalType: "bool",
        type: "bool",
        indexed: false,
      },
    ],
    name: "PythMarketRegistered",
  },
  { type: "error", inputs: [], name: "DeadlineInPast" },
  { type: "error", inputs: [], name: "DeadlineNotReached" },
  { type: "error", inputs: [], name: "InsufficientCreatorDeposit" },
  { type: "error", inputs: [], name: "InsufficientFee" },
  { type: "error", inputs: [], name: "MarketAlreadyFunded" },
  { type: "error", inputs: [], name: "MarketAlreadyRegistered" },
  { type: "error", inputs: [], name: "MarketAlreadyResolved" },
  { type: "error", inputs: [], name: "MarketAlreadyVoided" },
  { type: "error", inputs: [], name: "MarketNotRegistered" },
  { type: "error", inputs: [], name: "NotCreator" },
  { type: "error", inputs: [], name: "NotPythMarket" },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
  { type: "error", inputs: [], name: "Unauthorized" },
  { type: "error", inputs: [], name: "ZeroAmount" },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// VerityOptimisticResolver
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const verityOptimisticResolverAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_usdc", internalType: "address", type: "address" },
      { name: "_factory", internalType: "address", type: "address" },
      { name: "_arbitrator", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "FACTORY",
    outputs: [
      {
        name: "",
        internalType: "contract VerityMarketFactory",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "USDC",
    outputs: [{ name: "", internalType: "contract IERC20", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "arbitrator",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "disputeResolution",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "beneficiary", internalType: "address", type: "address" },
    ],
    name: "disputeResolutionFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "disputeWindow",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "marketId", internalType: "bytes32", type: "bytes32" }],
    name: "finalizeResolution",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    name: "proposals",
    outputs: [
      { name: "proposer", internalType: "address", type: "address" },
      {
        name: "proposedOutcomeIndex",
        internalType: "uint256",
        type: "uint256",
      },
      { name: "proposalTime", internalType: "uint256", type: "uint256" },
      { name: "disputed", internalType: "bool", type: "bool" },
      { name: "disputer", internalType: "address", type: "address" },
      { name: "finalized", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      {
        name: "proposedOutcomeIndex",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "proposeResolution",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "beneficiary", internalType: "address", type: "address" },
      {
        name: "proposedOutcomeIndex",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "proposeResolutionFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "resolutionBond",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "marketId", internalType: "bytes32", type: "bytes32" },
      { name: "winningOutcomeIndex", internalType: "uint256", type: "uint256" },
    ],
    name: "resolveDisputedMarket",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_arbitrator", internalType: "address", type: "address" }],
    name: "setArbitrator",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_window", internalType: "uint256", type: "uint256" }],
    name: "setDisputeWindow",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_bond", internalType: "uint256", type: "uint256" }],
    name: "setResolutionBond",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newArbitrator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "ArbitratorUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "finalOutcomeIndex",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "winner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "payoutAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "DisputeResolved",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newWindow",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "DisputeWindowUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newBond",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "ResolutionBondUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "disputer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "disputeTime",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "ResolutionDisputed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "finalOutcomeIndex",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "ResolutionFinalized",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "marketId",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "proposer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "proposedOutcomeIndex",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "proposalTime",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "ResolutionProposed",
  },
  { type: "error", inputs: [], name: "DisputeNotActive" },
  { type: "error", inputs: [], name: "DisputeWindowActive" },
  { type: "error", inputs: [], name: "DisputeWindowExpired" },
  { type: "error", inputs: [], name: "MarketAlreadyResolved" },
  { type: "error", inputs: [], name: "MarketNotExpired" },
  { type: "error", inputs: [], name: "ProposalAlreadyDisputed" },
  { type: "error", inputs: [], name: "ProposalAlreadyExists" },
  { type: "error", inputs: [], name: "ProposalAlreadyFinalized" },
  { type: "error", inputs: [], name: "ProposalDoesNotExist" },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
  { type: "error", inputs: [], name: "Unauthorized" },
] as const
